### ISSUE TITLE
DOCS - write docs/proj1rubricComments.pdf

### ISSUE THREAD

**Issue by shahleon** [shahleon/smart-todo#22]
Write a 2-page pdf on the connection between the items in the rubric and the Linux Kernel best practices. Add that document to your repo as docs/proj1rubricComments.pdf. Write that pdf using [this template](https://www.overleaf.com/latex/templates/association-for-computing-machinery-acm-sig-proceedings-template/bmvfhcdnxfty)
Not "nearly" this template. This template. Learn Latex. Hit: use [overleaf](https://www.overleaf.com/).

**Comment by shahleon** [comment]
Write a 2-page pdf on the connection between the items in the rubric and the Linux Kernel best practices. Add that document to your repo as docs/proj1rubricComments.pdf. Write that pdf using [this template](https://www.overleaf.com/latex/templates/association-for-computing-machinery-acm-sig-proceedings-template/bmvfhcdnxfty) 
Not "nearly" this template. This template. Learn Latex. Hit: use [overleaf](https://www.overleaf.com/).

**Comment by janet743** [comment]
Thank you for the help proofreading!
